#设置启用的环境
spring:
  profiles:
    active: pro

---
#多环境开发
#开发
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 80

---

#生产
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 81

---
#测试
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82
